name: draft_game
description: Cross-platform Draft Game client.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  checkers_ai:
    path: ../../packages/checkers_ai
  checkers_engine:
    path: ../../packages/checkers_engine
  flutter:
    sdk: flutter
  game_session:
    path: ../../packages/game_session

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
